name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn
      - run: yarn test
      - run: yarn build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - name: "Publish to Node Package Manager"
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@eunchurn"
          npm config list
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc
          npm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Setup actions"
        uses: actions/checkout@v3
      - name: "npm/registry setup"
        uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@eunchurn'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_GITHUB_TOKEN}}
      - run: yarn
      - name: "Publish to Github Package Registry"
        run: |
          echo "registry=https://npm.pkg.github.com/eunchurn" >> ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_GITHUB_TOKEN}}
